spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mslog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
#  sql:
#    init.mode: always

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  session:
    timeout: 86400

mixoo:
  jwt-key: "iFhqOiuUlf81xlqH4I5EBLq4iEmLY6HB41O5QZ7QfVg="

server:
  servlet:
    session:
      cookie:
        max-age: 172800
