### 회원가입

POST http://localhost:8080/auth/signup
Content-type: application/json

{
  "name" : "백민수",
  "email" : "minxoo@gmail.com",
  "password" : "1234"
}



### 로그인

POST http://localhost:8080/auth/login
Content-type: application/x-www-form-urlencoded

username=minxoo@gmail.com&password=1234&remember=1




### 메인 페이지

GET http://localhost:8080